const GAME_WIDTH = 288;
const GAME_HEIGHT = 512;
const GRAVITY = 0.2;
const FPS =60;
const GAME_SPEED =1;
const GAME_GRAVITY =0.2;
const FLAP_VELOCITY =10;
const PIPE_DISTANCE =180;
export{ GAME_GRAVITY, GAME_HEIGHT, GRAVITY, FPS, GAME_SPEED, FLAP_VELOCITY, GAME_WIDTH, PIPE_DISTANCE };